test_format = 1.0

[default]

    exclude = ["install.private"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server_name = "domain.tld"

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.15f4690b.name = "Upgrade from 0.9.9"
    test_upgrade_from.15f4690b.args.domain = "domain.tld"
    test_upgrade_from.15f4690b.args.server_name = "domain.tld"
    test_upgrade_from.15f4690b.args.registration = true
