test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.15f4690b.name = "Upgrade from 0.9.9"